name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    #   - uses: actions/setup-node@v3
    #     with:
    #       node-version: 16
    #       cache: npm
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.3
      - run: pwd
      - run: ls ../
      - run: pnpm i
    #   - run: npm run lint
    #   - run: npm run test
      - uses: fregante/daily-version-action@v2
        # TODO: 最新版ではタグがないときのエラー処理がまた抜けてるので一旦コミットで指定
        name: Create tag if necessary
        id: daily-version
      - run: pnpm run build
      - name: Update manifest.json
        run: |
          pnpx dot-json@1 dist/manifest.json version ${{ steps.daily-version.outputs.version }}
      - run: node deploy.js
      - name: Submit
        run: |
          npx chrome-webstore-upload-cli@2 upload --source extension.zip --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.daily-version.outputs.version }}
          generate_release_notes: true
          files: extension.zip
